name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
      - name: install pkg
        run: |
          npm install
          npm install hexo-cli -g
      - name: build app
        run: npm run build
      - name: scp action
        uses: betanzos/scp-upload@v1
        with:
          source: "public/"
          host: 124.223.38.61
          port: 22
          username: root
          key: ${{ secrets.SSH_KEY }}
          remote_dir: "/www"
          recursive: true
