# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
      - name: install pkg
        run: |
          npm install
          npm install hexo-cli -g
      - name: build app
        run: npm run build
      - name: copy doc
        uses: siva1024/scp-deployer@v1.0
        with:
          # ssh remote host
          host: ${{ secrets.REMOTE_HOST }}
          # ssh remote user
          username: root
          # ssh remote port
          port: 22 # optional, default is 22
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
           key: ${{ secrets.SSH_KEY }} # optional
          # ssh remote password
          password: ${{secrets.REMOTE_PASS}} # optional
          # source to copy from
          source: "public/" # optional
          # destination to download on server
          target: "www" # optional
