name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
      - name: install pkg
        run: |
          npm install
          npm install hexo-cli -g
      - name: build app
        run: npm run build
      - name: copy doc
        uses: siva1024/scp-deployer@v1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: "root"
          port: 22
          key: ${{ secrets.SSH_KEY }}
          password: ${{secrets.REMOTE_PASS}}
          source: "public/"
          target: "/www"
